extends:
  # https://github.com/standard/eslint-config-standard-with-typescript
  - 'standard-with-typescript'
  # https://github.com/typescript-eslint/typescript-eslint/blob/master/docs/getting-started/linting/README.md
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
env:
  commonjs: true
  es6: true
  node: true
  jest: true
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2019
  project: './tsconfig.test.json'
  sourceType: module
rules:
  # Object literal types are widely used in the common modules, and substituting for interfaces is not always trivial.
  '@typescript-eslint/consistent-type-definitions': off
  # According to its developer this rule is in "a broken state".
  # See warning at https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/indent.md
  '@typescript-eslint/indent': off
  # This rule will be disabled in the next release of eslint-config-standard-with-typescript.
  # See https://github.com/standard/eslint-config-standard-with-typescript/issues/217
  '@typescript-eslint/require-await': off
  # This rule conflicts with a SonarCloud rule sonarlint(typescript:S4326).
  '@typescript-eslint/return-await': off
  '@typescript-eslint/unbound-method': off
