service: personal-account-backend
useDotenv: true

plugins:
  - serverless-webpack
  - serverless-offline-dotenv
  - serverless-offline
  - serverless-openapi-documentation-v2

package:
  individually: false

provider:
  name: aws
  runtime: nodejs14.x
  architecture: arm64
  stage: ${opt:stage, 'local'}
  region: ${env:SLS_REGION, 'us-east-1'}
  timeout: 30
  memorySize: 128
  profile: bruno.administrator
  environment: ${file(./serverless.environment.yml):environment}

custom: ${file(./serverless.custom.yml):custom}
functions: ${file(./serverless.functions.yml):functions}
resources: ${file(./serverless.resources.yml):resources}

configValidationMode: off
