/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface CreateBankAccountOkResponse {
  status: "OK";
  message: string;
  result: CreateBankAccountOkResult;
}
export interface CreateBankAccountOkResult {
  id: string;
  [k: string]: unknown;
}
/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type CreateBankAccountRequest = CreateBankAccountRequestData;

export interface CreateBankAccountRequestData {
  bankNumber?: string;
  agencyCode?: string;
  accountNumber?: string;
  accountCheckDigit?: string;
  type?: "checking" | "savings";
  [k: string]: unknown;
}
