openapi: 3.0.0
components:
  schemas:
    CreateBankAccountRequest:
      title: Create Bank Account Request
      type: object
      properties:
        bankNumber:
          type: string
          minLength: 3
          maxLength: 3
        agencyCode:
          type: string
        accountNumber:
          type: string
        accountCheckDigit:
          type: string
          minLength: 1
          maxLength: 2
        type:
          type: string
          enum:
            - checking
            - savings
      additionalProperties: false
      required:
        - bankNumber
        - agencyCode
        - accountNumber
        - accountCheckDigit
        - type
    CreateBankAccountOkResponse:
      title: Create Bank Account Ok Response
      type: object
      properties:
        status:
          type: string
          enum:
            - OK
        message:
          type: string
        result:
          allOf:
            - type: object
              properties:
                id:
                  type: string
              required:
                - id
      required:
        - message
        - result
        - status
      additionalProperties: false
  securitySchemes: {}
info:
  title: Personal Account Backend
  description: ''
  version: '1.2'
servers: []
paths:
  /bank-account:
    post:
      operationId: createBankAccount
      summary: Create Bank Account
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateBankAccountRequest'
        description: Create a bank account for a given existing bank
      parameters: []
      responses:
        '201':
          description: Status 201 Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateBankAccountOkResponse'
